# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Search-Indexer
version:      0.71
version_from: lib/Search/Indexer.pm
installdirs:  site
requires:
    BerkeleyDB:                    0.25
    Search::QueryParser:           0.91

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
